tasks:
  - name: aws-cli
    command: |
      if ! command -v aws &> /dev/null; then
        echo "Installing AWS CLI..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        sudo ./aws/install
        rm -rf awscliv2.zip aws
        echo "AWS CLI installed and the zip file deleted"
      else
        echo "AWS CLI already installed."
      fi

      aws --version
