tasks:
  - name: aws-cli
    command: |
      if ! command -v aws &> /dev/null; then
        echo "Installing AWS CLI..."
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        sudo ./aws/install
        rm -rf awscliv2.zip aws
        echo "AWS CLI installed and the zip file deleted"
      else
        echo "AWS CLI already installed."
      fi

      aws --version

      ### Add auto-prompt to shell config if not already added
      
      if ! grep -q "AWS_CLI_AUTO_PROMPT=on-partial" ~/.bashrc; then
        echo 'export AWS_CLI_AUTO_PROMPT=on-partial' >> ~/.bashrc
      fi

      export AWS_CLI_AUTO_PROMPT=on-partial  # For current shell
      echo "Auto-prompt is set to: $AWS_CLI_AUTO_PROMPT"
      aws --version
